#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and on the 9th iteration "Hi" will be on a new line
x=1
while [ $x -le 10 ]
do
if [ $x -eq 9 ]
then
echo "Best School"
echo "Hi"
else 
echo "Best School"
fi
x=$((x + 1))
((i++))
done
