#!/usr/bin/env bash
# This script loops from 1 to 10 and;
# displays bad luck for tbe 4th loop
# displays good luck for the 8th loop iteration
# displays Best School for the other iteration
i=1
while [[ $i -le 10 ]]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
	echo "good luck"
else
echo "Best School"
fi
done
